# Site Info
title: Jungtae Kim Blog
tagline: 'Jungtae Kim Blog'
description: '스타트업과 새로운 기술, 그리고 라이프 스타일에 대해 이야기합니다.'
baseurl: ""
url: http://jungtaejtkim.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Jungtae Kim
  description: 스타트업과 새로운 기술, 그리고 라이프 스타일에 대해 이야기합니다.
  gravatar: dc3040b3d53d20e89643cf7035ba9866
  contact:
    linkedin:  https://www.linkedin.com/in/jungtae-kim-77810112b/
    # github:    https://github.com/jungtaejtkim
    facebook:  https://www.facebook.com/windjtk
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:     jungtae.jt.kim@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - ''

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/hikikomori-boy.png
  caption: 

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'jtkim' # leave blank if you don't want disqus

